name: fastai-environment
channels:
  - fastai
  - pytorch
  - conda-forge
  - default
dependencies:
  - python >= 3.6
  - jupyterlab
  - jupyterhub
  - nodejs 
  - jupyterlab-git
  - nb_conda
  - pytorch-cpu
  - fastai
  - pip:
    - ipywidgets
    - ipyleaflet
    - sklearn
    - tushare
    - numpy
    - pandas
    - scipy
    - matplotlib
    - plotly
    - statsmodels
    - seaborn
    - pillow
    - keras
    - theano
    - tensorflow
